REVOKE ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE USER, CREATE VIEW,
       DROP, EVENT, FILE, GRANT OPTION, INDEX, PROCESS, REFERENCES, RELOAD,
       REPLICATION CLIENT, REPLICATION SLAVE, SHOW DATABASES, SHOW VIEW,
       SHUTDOWN, SUPER, TRIGGER,
       CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE   -- махни от списъка, ако тестовете покажат, че се ползват
ON *.* FROM 'emart2'@'176.12.36.172';

REVOKE ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE USER, CREATE VIEW,
       DROP, EVENT, FILE, GRANT OPTION, INDEX, PROCESS, REFERENCES, RELOAD,
       REPLICATION CLIENT, REPLICATION SLAVE, SHOW DATABASES, SHOW VIEW,
       SHUTDOWN, SUPER, TRIGGER,
       CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE   -- махни от списъка, ако тестовете покажат, че се ползват
ON *.* FROM 'emart2'@'217.174.61.229';

REVOKE ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE USER, CREATE VIEW,
       DROP, EVENT, FILE, GRANT OPTION, INDEX, PROCESS, REFERENCES, RELOAD,
       REPLICATION CLIENT, REPLICATION SLAVE, SHOW DATABASES, SHOW VIEW,
       SHUTDOWN, SUPER, TRIGGER,
       CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE   -- махни от списъка, ако тестовете покажат, че се ползват
ON *.* FROM 'emart2'@'5.75.215.12';

REVOKE ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE USER, CREATE VIEW,
       DROP, EVENT, FILE, GRANT OPTION, INDEX, PROCESS, REFERENCES, RELOAD,
       REPLICATION CLIENT, REPLICATION SLAVE, SHOW DATABASES, SHOW VIEW,
       SHUTDOWN, SUPER, TRIGGER,
       CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE   -- махни от списъка, ако тестовете покажат, че се ползват
ON *.* FROM 'emart2'@'5.75.229.53';

REVOKE ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE USER, CREATE VIEW,
       DROP, EVENT, FILE, GRANT OPTION, INDEX, PROCESS, REFERENCES, RELOAD,
       REPLICATION CLIENT, REPLICATION SLAVE, SHOW DATABASES, SHOW VIEW,
       SHUTDOWN, SUPER, TRIGGER,
       CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE   -- махни от списъка, ако тестовете покажат, че се ползват
ON *.* FROM 'emart2'@'77.70.25.62';

REVOKE ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE USER, CREATE VIEW,
       DROP, EVENT, FILE, GRANT OPTION, INDEX, PROCESS, REFERENCES, RELOAD,
       REPLICATION CLIENT, REPLICATION SLAVE, SHOW DATABASES, SHOW VIEW,
       SHUTDOWN, SUPER, TRIGGER,
       CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE   -- махни от списъка, ако тестовете покажат, че се ползват
ON *.* FROM 'emart2'@'78.46.72.230';

REVOKE ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE USER, CREATE VIEW,
       DROP, EVENT, FILE, GRANT OPTION, INDEX, PROCESS, REFERENCES, RELOAD,
       REPLICATION CLIENT, REPLICATION SLAVE, SHOW DATABASES, SHOW VIEW,
       SHUTDOWN, SUPER, TRIGGER,
       CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE   -- махни от списъка, ако тестовете покажат, че се ползват
ON *.* FROM 'emart2'@'128.140.58.199';

REVOKE ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE USER, CREATE VIEW,
       DROP, EVENT, FILE, GRANT OPTION, INDEX, PROCESS, REFERENCES, RELOAD,
       REPLICATION CLIENT, REPLICATION SLAVE, SHOW DATABASES, SHOW VIEW,
       SHUTDOWN, SUPER, TRIGGER,
       CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE   -- махни от списъка, ако тестовете покажат, че се ползват
ON *.* FROM 'emart2'@'localhost';

-- REVOKE ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE USER, CREATE VIEW,
--        DROP, EVENT, FILE, GRANT OPTION, INDEX, PROCESS, REFERENCES, RELOAD,
--        REPLICATION CLIENT, REPLICATION SLAVE, SHOW DATABASES, SHOW VIEW,
--        SHUTDOWN, SUPER, TRIGGER,
--        CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE   -- махни от списъка, ако тестовете покажат, че се ползват
-- ON *.* FROM 'emart2'@'5.53.240.97';